name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Шаг для проверки репозитория из GitHub

    - name: Build Docker Containers
      run: |
        docker-compose -f $GITHUB_WORKSPACE/docker-compose.yml up -d --build

    - name: Sleep for 40 seconds
      run: sleep 40

    - name: Run Checkstyle
      run: mvn validate

    - name: Build Maven Project (Without Checkstyle)
      run: mvn clean package -Dmaven.checkstyle.skip=true
